[project]
name = "pypne"
version = "0.0.34"
dependencies = ["numpy"]
authors = [{ name = "Jinping Yang", email = "12227053@zju.edu.cn" }]
description = "Python package for network extraction"
keywords = ["pore-network", "network-extraction"]
requires-python = ">=3.13,<3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]
license = "Apache-2.0"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/yojeep/pypne"
Repository = "https://github.com/yojeep/pypne"
Issues = "https://github.com/yojeep/pypne/issues"

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"


[tool.scikit-build]
cmake.source-dir = "."
cmake.args = ["-G", "Ninja"]
cmake.build-type = "Release"

### 0.0.13 is the last version that supports Centos7 !!!
### 0.0.15 is the last version that only use single thread !!!
[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"

[tool.cibuildwheel.linux]
archs = ["auto64"]
#
#[tool.cibuildwheel.macos]
#archs = ["auto64"]
#
[tool.cibuildwheel.windows]
archs = ["auto64"]

[tool.scikit-build.build]
tool-args = ["-j0"]
