[build-system]
requires = ["scikit-build-core","pybind11","ninja"]
build-backend = "scikit_build_core.build"

[project]
name = "pypne"
version = "0.0.19"
requires-python = ">=3.8"


[tool.scikit-build]
cmake.source-dir = "."
cmake.args = ["-G", "Ninja"]
cmake.build-type = "Release"

### 0.0.13 is the last version that supports Centos7 !!!
### 0.0.15 is the last version that only use single thread !!!
[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"



[tool.cibuildwheel.linux]
archs = ["auto64"]
#
#[tool.cibuildwheel.macos]
#archs = ["auto64"]
#
[tool.cibuildwheel.windows]
archs = ["auto64"]

#environment = { PIP_CONFIG_SETTINGS="build_ext -j4" }

